In [2]:
# Basic Python

In [3]:
# 1. Split this string

In [4]:
s = "Hi there Sam!"
print(s.split())

['Hi', 'there', 'Sam!']


In [5]:
#2. Use .format() to print the following string.

In [6]:
#Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.


In [8]:
#3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [10]:
#Numpy

In [11]:
import numpy as np

In [12]:
zeroArr = np.zeros(10)
print(zeroArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
fiveArr = np.ones(10) * 5
print(fiveArr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [14]:
#5. Create an array of all the even integers from 20 to 35

In [15]:
evenIntegers = [i for i in range(20, 35) if i % 2 == 0]
print(evenIntegers)

[20, 22, 24, 26, 28, 30, 32, 34]


In [16]:
#6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
import numpy as np

matrix = np.arange(0, 9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#7. Concatinate a and b
#a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate((a,b), axis = None))

[1 2 3 4 5 6]


In [20]:
#Pandas

In [21]:
#8. Create a dataframe with 3 rows and 2 columns

In [22]:
import pandas as pd

In [23]:
data_frame = pd.DataFrame(index=['row1','row2','row3'], columns=['column1', 'column2'])
print(data_frame)

     column1 column2
row1     NaN     NaN
row2     NaN     NaN
row3     NaN     NaN


In [24]:
#9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [25]:
from datetime import date, timedelta

startDate = date(2023, 1, 1)
endDate = date(2023, 2, 11)

def dates_btw_twodates(start_date, end_date):
    for i in range(int((end_date - start_date).days)):
        yield start_date + timedelta(i)
for i in dates_btw_twodates(startDate, endDate):
    print(i)

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


In [26]:
#10. Create 2D list to DataFrame

In [27]:
#lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [28]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
data = zip(lists)
dataFrame = pd.DataFrame(data, columns=["d"])
print(dataFrame)

              d
0  [1, aaa, 22]
1  [2, bbb, 25]
2  [3, ccc, 24]
